# Replace these with your actual Telegram bot credentials.
TELEGRAM_TOKEN = 'YOUR_TELEGRAM_TOKEN'
TELEGRAM_CHAT_ID = 'YOUR_TELEGRAM_CHAT_ID'

# Arbitrage threshold (example: 30% spread)
ARBITRAGE_THRESHOLD = 0.30

# List of tokens to monitor (use token symbols as used by the exchanges)
WATCHLIST = [
    'ALPHAOFSOL'  # Example token
]

# Exchange API Configurations
BINANCE_API_KEY = 'YOUR_BINANCE_API_KEY'
BINANCE_API_SECRET = 'YOUR_BINANCE_API_SECRET'

BYBIT_API_KEY = 'YOUR_BYBIT_API_KEY'
BYBIT_API_SECRET = 'YOUR_BYBIT_API_SECRET'

KUCOIN_API_KEY = 'YOUR_KUCOIN_API_KEY'
KUCOIN_API_SECRET = 'YOUR_KUCOIN_API_SECRET'
KUCOIN_API_PASSPHRASE = 'YOUR_KUCOIN_API_PASSPHRASE'

GATEIO_API_KEY = 'YOUR_GATEIO_API_KEY'
GATEIO_API_SECRET = 'YOUR_GATEIO_API_SECRET'

BITGET_API_KEY = 'YOUR_BITGET_API_KEY'
BITGET_API_SECRET = 'YOUR_BITGET_API_SECRET'
BITGET_API_PASSPHRASE = 'YOUR_BITGET_API_PASSPHRASE'

OKX_API_KEY = 'YOUR_OKX_API_KEY'
OKX_API_SECRET = 'YOUR_OKX_API_SECRET'
OKX_API_PASSPHRASE = 'YOUR_OKX_API_PASSPHRASE'

MEXC_API_KEY = 'YOUR_MEXC_API_KEY'
MEXC_API_SECRET = 'YOUR_MEXC_API_SECRET'